version: "3.8"
services:
  mongodb:
    container_name: mongodb
    image: mongo:7.0.1-nanoserver
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
    driver: local